/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiInsight: typeof import('./components/ui/AiInsight.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    CashFlowAreaChart: typeof import('./components/charts/CashFlowAreaChart.vue')['default']
    CashFlowTuner: typeof import('./components/panels/CashFlowTuner.vue')['default']
    CashInBankChart: typeof import('./components/charts/CashInBankChart.vue')['default']
    DashboardLayout: typeof import('./components/layout/DashboardLayout.vue')['default']
    ForecastTuner: typeof import('./components/panels/ForecastTuner.vue')['default']
    GenerateButton: typeof import('./components/ui/GenerateButton.vue')['default']
    GoalCompletionChart: typeof import('./components/charts/GoalCompletionChart.vue')['default']
    KpiCard: typeof import('./components/cards/KpiCard.vue')['default']
    NetflowChart: typeof import('./components/charts/NetflowChart.vue')['default']
    OutputSnapshot: typeof import('./components/panels/OutputSnapshot.vue')['default']
    ProfitLossChart: typeof import('./components/charts/ProfitLossChart.vue')['default']
    RevenueExpensesChart: typeof import('./components/charts/RevenueExpensesChart.vue')['default']
    SliderControl: typeof import('./components/ui/SliderControl.vue')['default']
  }
}
